tour-of-heroes-api/config/routes.rb
Rails.application.routes.draw do
  resources :heroes

end

tour-of-heroes-api/app/models/hero.rb
class Hero < ActiveRecord::Base
end

tour-of-heroes-api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

tour-of-heroes-api/app/controllers/heroes_controller.rb
class HeroesController < ApplicationController
  before_action :set_hero, only: [:show, :edit, :update, :destroy]

  # GET /heroes
  # GET /heroes.json
  def index
    @heroes = Hero.all
  end

  # GET /heroes/1
  # GET /heroes/1.json
  def show
  end

  # GET /heroes/new
  def new
    @hero = Hero.new
  end

  # GET /heroes/1/edit
  def edit
  end

  # POST /heroes
  # POST /heroes.json
  def create
    @hero = Hero.new(hero_params)

    respond_to do |format|
      if @hero.save
        format.html { redirect_to @hero, notice: 'Hero was successfully created.' }
        format.json { render :show, status: :created, location: @hero }
      else
        format.html { render :new }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heroes/1
  # PATCH/PUT /heroes/1.json
  def update
    respond_to do |format|
      if @hero.update(hero_params)
        format.html { redirect_to @hero, notice: 'Hero was successfully updated.' }
        format.json { render :show, status: :ok, location: @hero }
      else
        format.html { render :edit }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heroes/1
  # DELETE /heroes/1.json
  def destroy
    @hero.destroy
    respond_to do |format|
      format.html { redirect_to heroes_url, notice: 'Hero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hero
      @hero = Hero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hero_params
      params.require(:hero).permit(:name)
    end
end

tour-of-heroes-api/app/helpers/application_helper.rb
module ApplicationHelper
end

tour-of-heroes-api/app/helpers/heroes_helper.rb
module HeroesHelper
end

tour-of-heroes-api/app/views/heroes/_form.html.erb
<%= form_for(@hero) do |f| %>
  <% if @hero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hero.errors.count, "error") %> prohibited this hero from being saved:</h2>

      <ul>
      <% @hero.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tour-of-heroes-api/app/views/heroes/edit.html.erb
<h1>Editing Hero</h1>

<%= render 'form' %>

<%= link_to 'Show', @hero %> |
<%= link_to 'Back', heroes_path %>

tour-of-heroes-api/app/views/heroes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Heroes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @heroes.each do |hero| %>
      <tr>
        <td><%= hero.name %></td>
        <td><%= link_to 'Show', hero %></td>
        <td><%= link_to 'Edit', edit_hero_path(hero) %></td>
        <td><%= link_to 'Destroy', hero, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hero', new_hero_path %>

tour-of-heroes-api/app/views/heroes/new.html.erb
<h1>New Hero</h1>

<%= render 'form' %>

<%= link_to 'Back', heroes_path %>

tour-of-heroes-api/app/views/heroes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hero.name %>
</p>

<%= link_to 'Edit', edit_hero_path(@hero) %> |
<%= link_to 'Back', heroes_path %>

tour-of-heroes-api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TourOfHeroesApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>